### ISSUE TITLE
Multiple selectable options text input

### ISSUE THREAD

**Issue by kevintc** [dbrekalo/fastselect#1]
Hello !

Great tool :) In your first example "Multiple selectable options", if I type : "fra" I get the correct option and I can select "France". However, when selecting "France", the input area is not cleared from the "fra" I just typed... 
Is there any way to avoid this kind of behavior ?

Thanks a lot :)

**Comment by dbrekalo** [comment]
Thanks for great feedback @kevintc!

Your suggestions definitely makes sense from UI perspective and are now implemented in plugin as default behavior. 

There are still cases where keeping query after item select makes sense. Following snippet should cover you then:

```javascript
$('select').fastselect({clearQueryOnSelect: false});
```
