### ISSUE TITLE
Reload the data when fast select opens every time

### ISSUE THREAD

**Issue by amrutrayabagi** [dbrekalo/fastselect#16]
Hi,

It seems fast select cache the data once it gets the data from server. So subsequent mouse clicks on the control gets me the old values.

How to force fastselect to load the data everytime user clicks on the control.? . The reason I am doing is becausem . my parameter to the server URL will be a combination of other  control values along with search text entered by user..

So whenever user opens/clicks the control it should reload the data every time using its get/ajax call.. I want to force this behavior..?

Is there a way..?

**Comment by vohrahul** [comment]
There's a property that you can pass to fastselect on initialization.
`loadOnce: true/false`

This should help you.
