### ISSUE TITLE
Add tags which are not exists

### ISSUE THREAD

**Issue by serajam** [dbrekalo/fastselect#4]
Please add a possibility to add tags which are not in the available list and submit them as text.

Thanks

**Comment by dbrekalo** [comment]
@serajam this is definitly high on priority list and will be implemented as soon as i make time.

**Comment by dbrekalo** [comment]
@serajam this is now available via "userOptionAllowed" option - please check demo site for example (http://dbrekalo.github.io/fastselect/#section-examples)
