### ISSUE TITLE
Autocomplete / search input :  word with accent or not

### ISSUE THREAD

**Issue by ponyx** [dbrekalo/fastselect#44]
Hi, 

I'm using fastselect for a french project so I have some problem when I'm searching an word with an accent. 
For example, if in my list I have the word "batelière" with accent, if I type "bateliere" without accent in the input result, the result is "not found".

Does it exist a solution for this issue ?

Thank you for your help.

**Comment by agencefacton** [comment]
Hi,

same question ?!

**Comment by dbrekalo** [comment]
Custom search logic can be implemented via "matcher" callback option when initialising your component:  
```js
$('select').fastselect({
	matcher: function(text, query) {
		// default implementation
        return text.toLowerCase().indexOf(query.toLowerCase()) > -1;
    }
});
```
Hope this helps!

**Comment by agencefacton** [comment]
Thank you, here is my code:

function normalizeString(string) {
			return string.split('').map(function (letter) {
					let i = this.accents.indexOf(letter);
					return (i !== -1) ? this.out[i] : letter;
				}.bind({
					accents: 'ÀÁÂÃÄÅĄàáâãäåąßÒÓÔÕÕÖØÓòóôõöøóÈÉÊËĘèéêëęðÇĆçćÐÌÍÎÏìíîïÙÚÛÜùúûüÑŃñńŠŚšśŸÿýŽŻŹžżź',
					out: 'AAAAAAAaaaaaaaBOOOOOOOOoooooooEEEEEeeeeeeCCccDIIIIiiiiUUUUuuuuNNnnSSssYyyZZZzzz'
				})
			).join('');
		}

		`$('select').fastselect({
			matcher: function (text, query) {
				text = normalizeString(text);
				query = normalizeString(query);
				return text.toLowerCase().indexOf(query.toLowerCase()) > -1;
			}
		});`

**Comment by ponyx** [comment]
Perfect! Thanks a lot!!!
